import db_nimternalsql/like

doAssert matchesLike("", "")
doAssert matchesLike("", "%")
doAssert matchesLike("Grummel", "%")
doAssert matchesLike("Grummel", "%_")
doAssert matchesLike("Grummel", "%umme%")
doAssert matchesLike("Grummel", "%ru%me%")
doAssert matchesLike("Grummel", "Grum%mel")
doAssert matchesLike("Grummel", "Grum%mel")
doAssert matchesLike("Grummel", "Grum_el")
doAssert matchesLike("Grummel", "Gr%l")
doAssert matchesLike("Grummel", "Gr%m%l")
doAssert matchesLike("Grummel", "Gru__el")
doAssert matchesLike("Blabli", "%l_")
doAssert matchesLike("Blabli", "%l%")
doAssert matchesLike("Sql", "Sq_")
doAssert matchesLike("Abrakadabra", "%ra_ad%")

doAssert not matchesLike(" ", "")
doAssert not matchesLike("", "_")
doAssert not matchesLike("Grummel", "%umme")
doAssert not matchesLike("Grummel", "umme%")
doAssert not matchesLike("Grummel", "Gru_el")
doAssert not matchesLike("Grummel", "Gr%ml")
doAssert not matchesLike("Blabli", "%la_")
doAssert not matchesLike("Abrakadabra", "%ra_ab%")
